// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hh9xYJGtlsSQTvJjzKQlrWPnBaxh1uk',
    appId: '1:712622845147:android:ed23d4c3447d1fc9a770fe',
    messagingSenderId: '712622845147',
    projectId: 'elektron-poliklinika',
    databaseURL: 'https://elektron-poliklinika-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elektron-poliklinika.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRFm8Jsj2SCpk5aYy800YbcDJM5xR0i_4',
    appId: '1:712622845147:ios:81cab0d002487d34a770fe',
    messagingSenderId: '712622845147',
    projectId: 'elektron-poliklinika',
    databaseURL: 'https://elektron-poliklinika-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elektron-poliklinika.appspot.com',
    iosBundleId: 'com.example.team2',
  );
}
